const datosLecciones = {
  lecciones: [
    {
      id: 1,
      nombre: "leccion 1",
      palabras: [
        { aleman: "aussehen, sah aus, hat ausgesehen", espanol: "verse" },
        { aleman: "die Größe", espanol: "la talla" },
        { aleman: "intelligent", espanol: "inteligente" },
        { aleman: "lieb", espanol: "amable" },
        { aleman: "lustig", espanol: "divertido" },
        { aleman: "nett", espanol: "agradable" },
        { aleman: "leider", espanol: "lamentablemente" },
        { aleman: "vorbei sein", espanol: "haber terminado" },
        { aleman: "feiern, feierte, hat gefeiert", espanol: "celebrar" },
        { aleman: "fotografieren, fotografierte, hat fotografiert", espanol: "fotografiar" },
        { aleman: "die Reise", espanol: "el viaje" },
        { aleman: "probieren, probierte, hat probiert", espanol: "probar" },
        { aleman: "surfen, surfte, hat gesurft", espanol: "hacer surf" },
        { aleman: "spielen, spielte, hat gespielt", espanol: "jugar" },
        { aleman: "der Urlaub", espanol: "las vacaciones" },
        { aleman: "die Arbeit", espanol: "el trabajo" },
        { aleman: "der Cousin", espanol: "el primo" },
        { aleman: "schicken, schickte, hat geschickt", espanol: "enviar" },
        { aleman: "der Spaß", espanol: "la diversión" },
        { aleman: "unterwegs sein", espanol: "estar de camino" },
        { aleman: "grillen, grillte, hat gegrillt", espanol: "hacer una barbacoa" },
        { aleman: "die Lust", espanol: "las ganas" },
        { aleman: "echt", espanol: "realmente" },
        { aleman: "der Krimi", espanol: "la novela policíaca" },
        { aleman: "lange", espanol: "mucho tiempo" },
        { aleman: "leidtun", espanol: "sentir" },
        { aleman: "sauer", espanol: "enfadado" },
        { aleman: "schon", espanol: "ya" },
        { aleman: "warten auf, wartete auf, hat gewartet (auf)", espanol: "esperar a" },
        { aleman: "der Unterschied", espanol: "la diferencia" },
        { aleman: "der Bus", espanol: "el autobús" },
        { aleman: "die U-Bahn", espanol: "el metro" },
        { aleman: "lügen, log, hat gelogen", espanol: "mentir" },
        { aleman: "pünktlich", espanol: "puntual" },
        { aleman: "So ein Qatsch!", espanol: "¡Qué tontería!" },
        { aleman: "sterben, starb, ist gestorben", espanol: "morir" },
        { aleman: "stimmen, stimmte, hat gestimmt", espanol: "ser cierto" },
        { aleman: "wecken, weckte, hat geweckt", espanol: "despertar" },
        { aleman: "ca.", espanol: "aproximadamente" },
        { aleman: "die Angst", espanol: "el miedo" },
        { aleman: "diskutieren, diskutierte, hat diskutiert", espanol: "discutir" },
        { aleman: "froh", espanol: "contento" },
        { aleman: "glücklich", espanol: "feliz" },
        { aleman: "klug", espanol: "listo" },
        { aleman: "lacehn, lachte, hat gelacht", espanol: "reír" },
        { aleman: "nervös", espanol: "nervioso" },
        { aleman: "die Note", espanol: "la nota" },
        { aleman: "plötzlich", espanol: "de repente" },
        { aleman: "die Prüfung", espanol: "el examen" },
        { aleman: "Silvester", espanol: "Nochevieja" },
        { aleman: "sogar", espanol: "incluso" },
        { aleman: "der Stress", espanol: "el estrés" },
        { aleman: "traurig", espanol: "triste" },
        { aleman: "unglücklich", espanol: "desafortunado" },
        { aleman: "verliebt sein", espanol: "estar enamorado" },
        { aleman: "weinen, weinte, hat geweint", espanol: "llorar" },
        { aleman: "zufrieden", espanol: "satisfecho" },
        { aleman: "unzufrieden", espanol: "insatisfecho" },
        { aleman: "schriftlich", espanol: "por escrito" },
        { aleman: "ausgehen, ging aus, ist ausgegangen", espanol: "salir" },
        { aleman: "ein paar", espanol: "algunos/as" },
        { aleman: "chaffen", espanol: "lograr" },
        { aleman: "anbieten, bot an, hat angeboten", espanol: "ofrecer" },
        { aleman: "bitten, bat, hat gebeten", espanol: "pedir" },
        { aleman: "das Taschengeld", espanol: "la paga" }
      ]
    },
    {
      id: 2,
      nombre: "leccion 2",
      palabras: [
        { aleman: "der Vorschlag", espanol: "la propuesta" },
        { aleman: "allein", espanol: "solo" },
        { aleman: "draußen", espanol: "afuera"  },
        { aleman: "fallen, fiel, ist gefallen", espanol: "caer" },
        { aleman: "fit sein", espanol: "estar en forma"},
        { aleman: "gefährlich sein", espanol: "ser peligroso"},
        { aleman: "gefährlich sein", espanol: "ser peligroso" },
        { aleman: "gewinnen, gewann, hat gewonnen", espanol: "ganar" },
        { aleman: "die Gruppe", espanol: "el grupo" },
        { aleman: "die Halle", espanol: "el pabellón" },
        { aleman: "möglich", espanol: "posible" },  
        { aleman: "spannend", espanol: "emocionante" },
        { aleman: "überall", espanol: "en todas partes" },
        { aleman: "der Verein", espanol: "el club" },
        { aleman: "voebereiten, bereitete vor, hat vorbereitet", espanol: "preparar" },
        { aleman: "anfangen, fing an, hat angefangen", espanol: "comenzar" },
        { aleman: "sich anmelden, meldete sich an, hat sich angemeldet", espanol: "inscribirse" },
        { aleman: "aufhören. hörte auf, hat aufgehört", espanol: "dejar de hacer algo" },
        { aleman: "beginnen, begann, hat begonnen", espanol: "empezar" },
        { aleman: "bekannt", espanol: "conocido/a" },
        { aleman: "damals", espanol: "en aquella época" },
        { aleman: "früher", espanol: "antiguamente" },
        { aleman: "gerade", espanol: "en este momento" },
        { aleman: "sich interessieren, interessierte sich, hat sich interessiert", espanol: "interesarse" },
        { aleman: "der Kurs", espanol: "el curso" },
        { aleman: "die maschine", espanol: "la máquina" },
        { aleman: "mitgehen, geh mit, ist mitgegangen", espanol: "acompañar" },
        { aleman: "mitspielen, spielte mit, hat mitgespielt", espanol: "jugar con" },
        { aleman: "der Reifen", espanol: "el neumático" },
        { aleman: "super", espanol: "super" },
        { aleman: "teilnehmen, nahm teil, hat teilgenommen", espanol: "participar" },
        { aleman: "trainieren, trainierte, hat trainiert", espanol: "entrenar" },
        { aleman: "träumen von, träumte von, hat geträumt (von)", espanol: "soñar con" },
        { aleman: "verletzt sein", espanol: "estar lesionado" },
        { aleman: "vorsichtig sein", espanol: "ser precavido"},
        { aleman: "der Wagen", espanol: "el coche" },
        { aleman: "aufpassen, passte aUF, hat aufgepasst", espanol: "prestar atención" },
        { aleman: "Lieblings-", espanol: "favorito" },
        { aleman: "manchmal", espanol: "a veces" },
        { aleman: "mehrere", espanol: "varios/as" },
        { aleman: "zeigen. zeigte, hat gezeigt", espanol: "mostrar" },
        { aleman: "vergessen, vergaß, hat vergessen", espanol: "olvidar" },
        { aleman: "versuchen, versuchte, hat versucht", espanol: "intentar" },
        { aleman: "Bescheid sagen", espanol: "informar" },
        { aleman: "einverstanden sein", espanol: "estar de acuerdo" },
        { aleman: "bestimmt", espanol: "seguro" },
        { aleman: "das Fahrrad", espanol: "la bicicleta" },
        { aleman: "das Geschenk", espanol: "el regalo" },
        { aleman: "der Platz", espanol: "la plaza" },
        { aleman: "dauern", espanol: "durar" },
        { aleman: "in der Nähe", espanol: "cerca" }
      ]
    },
   {
      id: 3,
      nombre: "leccion 3",
      palabras: [
        { aleman: "der Preis", espanol: "el premio" },
        { aleman: "der Wettbewerb", espanol: "el concurso" },
        { aleman: "wissen, wusste, hat gewusst", espanol: "saber" },
        { aleman: "das Instrument", espanol: "el instrumento" },
        { aleman: "das Stück", espanol: "la obra de teatro" },
        { aleman: "der Workshop", espanol: "el taller" },
        { aleman: "mitmachen, machte mit, hat mitgemacht", espanol: "participar" },
        { aleman: "bekommen, bekam, hat bekommen", espanol: "recibir" },
        { aleman: "die Hilfe", espanol: "la ayuda" },
        { aleman: "möglich", espanol: "posible" },
        { aleman: "der Raum", espanol: "sala" },
        { aleman: "organisieren. organisierte, hat organisiert", espanol: "organizar" },
        { aleman: "das Datum", espanol: "la fecha" },
        { aleman: "der Ausflug", espanol: "la excursión" },
        { aleman: "stattfinden, fand statt, hat stattgefunden", espanol: "tener lugar" },
        { aleman: "einladen, lud ein, hat eingeladen", espanol: "invitar" },
        { aleman: "planen, plante, hat geplant", espanol: "planear" },
        { aleman: "sollen, sollte", espanol: "deber" },
        { aleman: "üben, übte, hat geübt", espanol: "practicar" },
        { aleman: "wirklich", espanol: "realmente" },
        { aleman: "witzig", espanol: "gracioso" },
        { aleman: "sich ärgern, ärgerte sich, hat sich geärgert", espanol: "enfadarse" },
        { aleman: "sich ausruhen, ruhte sich aus, hat sich ausgeruht", espanol: "descansar" },
        { aleman: "sich beeilen, beeilte sich, hat sich beeilt", espanol: "darse prisa" },
        { aleman: "sich entscheiden, entschied sich, hat sich entschieden", espanol: "decidirse" },
        { aleman: "sich entschuldigen", espanol: "disculparse" },
        { aleman: "sich streiten, stritt sich, hat sich gestritten", espanol: "discutir" },
        { aleman: "sich freuen, freute sich, hat sich gefreut", espanol: "alegrarse" },
        { aleman: "sich trauen, traute sich, hat sich getraut", espanol: "atreverse" },
        { aleman: "einfach", espanol: "fácil" },
        { aleman: "sich fühlen, fühlte sich, hat sich gefühlt", espanol: "sentirse" },
        { aleman: "klappen, klappte, hat geklappt", espanol: "salir bien" },
        { aleman: "sich unterhalten, unterhielt sich, hat sich unterhalten", espanol: "charlar" },
        { aleman: "sich vorbereiten, bereitete sich vor, hat sich vorbereitet", espanol: "prepararse" },
        { aleman: "anfangen, fing an, hat angefangen", espanol: "comenzar" },
        { aleman: "bedeuten, bedeutete, hat bedeutet", espanol: "significar" },
        { aleman: "aktuell", espanol: "actual" },
        { aleman: "der Tipp", espanol: "el consejo" },
        { aleman: "begründen, begründete, hat begründet", espanol: "justificar" },
        { aleman: "berühmt", espanol: "famoso/a" },
        { aleman: "besonders", espanol: "especialmente" },
        { aleman: "dabei sein", espanol: "estar presente" },
        { aleman: "der Kontakt", espanol: "el contacto" },
        { aleman: "die Kosmetik", espanol: "la coméstica" },
        { aleman: "der Laptop", espanol: "el portátil" },
        { aleman: "mindestens", espanol: "al menos" },
        { aleman: "der Musiker", espanol: "el músico" },
        { aleman: "die Musikerin", espanol: "la música" },
        { aleman: "das Produkt", espanol: "el producto" },
        { aleman: "der Schauspieler", espanol: "el actor" },
        { aleman: "die Schauspielerin", espanol: "la actriz" },
        { aleman: "der Witz", espanol: "el chiste" },
        { aleman: "schließen, schloss, hat geschlossen", espanol: "cerrar" },
        { aleman: "aktiv", espanol: "activo" },
        { aleman: "chatten, chattete, hat gechattet", espanol: "chatear" },
        { aleman: "das Gerät", espanol: "el aparato" },
        { aleman: "herunterladen, lud herunter, hat heruntergeladen", espanol: "descargar" },
        { aleman: "im Internet surfen", espanol: "navegar en internet" },
        { aleman: "erlauben, erlaubte, hat erlaubt", espanol: "permitir" },
        { aleman: "die Erlaunis", espanol: "el permiso" },
        { aleman: "verbieten, verbot, hat verboten", espanol: "prohibir" },
        { aleman: "das Verbot", espanol: "la prohibicón" },
      ]
    },
   {
      id: 4,
      nombre: "leccion 4",
      palabras: [
        { aleman: "das Geschirr", espanol: "la vajilla" },
        { aleman: "komisch", espanol: "extraño" },
        { aleman: "kriegen, kriegte, hat gekriegt", espanol: "recibir" },
        { aleman: "das Rätsel", espanol: "el acertijo" },
        { aleman: "runterfallen, fielen runter, ist runtergefallen", espanol: "caer" },
        { aleman: "stehen bleiben", espanol: "detenerse" },
        { aleman: "das Spiel", espanol: "el partido" },
        { aleman: "verlieren, verlor, hat verloren", espanol: "perder" },
        { aleman: "wegbringen, brachte weg, hat weggebracht", espanol: "deshacerse de algo" },
        { aleman: "warum?", espanol: "¿por qué?" },
        { aleman: "abfahren, fuhr ab, ist abgefahren", espanol: "partir, salir" },
        { aleman: "früh", espanol: "temprano" },
        { aleman: "mitbringen, brachte mit, hat mitgebracht", espanol: "llevarse" },
        { aleman: "die Süßigkeiten", espanol: "las golosinas" },
        { aleman: "der Unfall", espanol: "el accidente" },
        { aleman: "verboten sein", espanol: "estar prohibido" },
        { aleman: "weil", espanol: "porque" },
        { aleman: "krank", espanol: "enfermo" },
        { aleman: "einpacken, packte ein, hat eingepackt", espanol: "empaquetar" },
        { aleman: "ich habe Hunger", espanol: "tengo hambre" },
        { aleman: "teilen", espanol: "compartir" },
        { aleman: "die Jugendherberge", espanol: "el albergue" },
        { aleman: "das Besteck", espanol: "la cubertería" },
        { aleman: "bringen, brachte, hat gebracht", espanol: "traer" },
        { aleman: "einziehen, zog ein, hat eingezogen", espanol: "mudarse" },
        { aleman: "enden", espanol: "terminar" },
        { aleman: "die Gabel", espanol: "el tenedor" },
        { aleman: "der Besuch", espanol: "la visita" },
        { aleman: "der Gast", espanol: "el invitado" },
        { aleman: "der Kühlschrank", espanol: "el frigorífico" }, 
        { aleman: "leihen, lieh, hat geliehen", espanol: "prestar" },
        { aleman: "der Löffel", espanol: "la cuchara" },
        { aleman: "das Messer", espanol: "el cuchillo" },
        { aleman: "nachts", espanol: "por la noche" },
        { aleman: "neben", espanol: "al lado de" },
        { aleman: "offen", espanol: "abierto" },
        { aleman: "sauber halten, hielt sauber, hat sauber gehalten", espanol: "mantener limpio" },
        { aleman: "tagsüber", espanol: "todo el día" },
        { aleman: "schließen, shloss, hat geschlossen", espanol: "cerrar" },
        { aleman: "die Wäsche", espanol: "la colada" },
        { aleman: "jemand, niemand", espanol: "alguien, nadie" },
        { aleman: "die Feier", espanol: "la celebración" },
        { aleman: "weggehen, ging weg, ist weggegangen", espanol: "irse" },
        { aleman: "der Moment", espanol: "el momento" },
        { aleman: "der Teller", espanol: "el plato" },
        { aleman: "der Koffer", espanol: "la maleta" },
        { aleman: "der Kontakt", espanol: "el contacto" },
        { aleman: "lang, länger, am längsten", espanol: "largo" },
        { aleman: "ich packe den Koffer", espanol: "hago la maleta" },
        { aleman: "packen, packte, hat gepackt", espanol: "empacar" },
        { aleman: "schwören, schwörte, hat geschwören", espanol: "jurar" },
        { aleman: "der See", espanol: "el lago" },
        { aleman: "das Ziel", espanol: "la meta, el objetivo" },
        { aleman: "bauen", espanol: "construir" },
        { aleman: "reisen, reiste, ist gereist", espanol: "viajar" }
        
      ]
    },
    {
      id: 5,
      nombre: "leccion 5",
      palabras: [
        { aleman: "auf jeden Fall", espanol: "por supuesto" },
        { aleman: "reich, reicher am reichsten", espanol: "rico" },
        { aleman: "als", espanol: "que" },
        { aleman: "hoch, höher, am höchsten", espanol: "alto" },
        { aleman: "beliebt, beliebter, am beliebtesten", espanol: "popular" },
        { aleman: "das Rad", espanol: "la bicileta" },
        { aleman: "genauso wie", espanol: "tan como" },
        { aleman: "auftreten, trat auf, ist aufgetretten", espanol: "actuar" },
        { aleman: "außerdem", espanol: "además de eso" },
        { aleman: "begeistern", espanol: "entusiasmar" },
        { aleman: "die Bühne", espanol: "el escenario" },
        { aleman: "endlich", espanol: "por fin" },
        { aleman: "erscheinen, erschien, ist erschienen", espanol: "aparecer" },
        { aleman: "die Mischung", espanol: "la mezcla" },
        { aleman: "realisieren, realisierte, hat realisiert", espanol: "realizar" },
        { aleman: "stehen, stand, ist gestanden", espanol: "estar de pide" },
        { aleman: "überall", espanol: "en todas partes" },
        { aleman: "unterschiedlich, unterschiedlicher, am unterschiedlichsten", espanol: "diferente" },
        { aleman: "die Welt", espanol: "el mundo" },
        { aleman: "die Freiheit", espanol: "la libertad" },
        { aleman: "der Himmel", espanol: "el cielo" },
        { aleman: "einige", espanol: "algunos/as" },
        { aleman: "gehen, ging, ist gegangen", espanol: "ir" },
        { aleman: "abholen, holte ab, hat abgeholt", espanol: "recoger" },
        { aleman: "dass", espanol: "que" },
        { aleman: "empfehlen, empfohl, hat empfohlen", espanol: "recomendar" },
        { aleman: "die Ordnung", espanol: "el orden" },
        { aleman: "Das ist in Ordnung", espanol: "Esto está bien" },
        { aleman: "teuer, teurer, am teuersten", espanol: "caro" },
        { aleman: "unbedingt", espanol: "obligatoriamente" }, 
        { aleman: "zwischen", espanol: "entre" },
        { aleman: "die Laune", espanol: "el humor" },
        { aleman: "die Anzeige", espanol: "el anuncio" },
        { aleman: "die Ausstellung ", espanol: "exposición" },
        { aleman: "der Eintritt", espanol: "la entrada" },
        { aleman: "kostenlos", espanol: "gratis" },
        { aleman: "das Programm", espanol: "el programa" },
        { aleman: "das Museum", espanol: "el museo" },
        { aleman: "stattfinden, fandet statt, hat stattgefunden", espanol: "tener lugar" },
        { aleman: "täglich", espanol: "diariamente" },
        { aleman: "viel mehr", espanol: "mucho más" },
        { aleman: "von... bis...", espanol: "desde hasta" },
        { aleman: "vorbeikommen, kam vorbei, ist vorbeigekommen", espanol: "pasar por" },
        { aleman: "der Fluss", espanol: "río" },
        { aleman: "die Veranstaltung", espanol: "el evento" },
        
      ]
    },
{
      id: 6,
      nombre: "leccion 6 ",
      palabras: [
        { aleman: "abgeben, gab ab, hat abgegeben", espanol: "entregar" },
        { aleman: "die Bahn", espanol: "el tren" },
        { aleman: "die Bücherei", espanol: "la librería" },
        { aleman: "die Dusche", espanol: "la ducha" },
        { aleman: "der Recyclinghof", espanol: "la planta de reciclaje" },
        { aleman: "die Reparatur", espanol: "la reparación" },
        { aleman: "reparieren, reparierte, hat repariert", espanol: "reparar" },
        { aleman: "tauschen, tauschte, hat getauscht", espanol: "intercambiar" },
        { aleman: "wegwerfen, warf weg, hat weggeworfen", espanol: "arrojar" },
        { aleman: "gemeinsam", espanol: "común" },
        { aleman: "die Umwelt", espanol: "el medioambiente" },
        { aleman: "umweltfreundlich", espanol: "ecologista" },
        { aleman: "das Verhalten", espanol: "el comportamiento" },
        { aleman: "das Gericht", espanol: "el plato de comida" },
        { aleman: "manche", espanol: "algunos/as" },
        { aleman: "niemand, jemand", espanol: "nadie, alguien" },
        { aleman: "viel, viele", espanol: "mucho/a, muchos/as" },
        { aleman: "die Butter", espanol: "la mantequilla" },
        { aleman: "ebenfalls", espanol: "igualmente" },
        { aleman: "sich ernähren, ernährte sich, hat sich ernährt", espanol: "la libertad" },
        { aleman: "die Ernährung", espanol: "la alimentación" },
        { aleman: "der/die Erwachsene", espanol: "el adulto, la adulta" },
        { aleman: "das Fett", espanol: "la grasa" },
        { aleman: "frisch, frischer, am frischesten", espanol: "fresco" },
        { aleman: "die Gesundheit", espanol: "la salud" },
        { aleman: "die Meinung", espanol: "la opinión" },
        { aleman: "schützen, schützte, hat geschützt", espanol: "proteger" },
        { aleman: "vegan", espanol: "vegano/a" },
        { aleman: "vegetarisch", espanol: "vegetariano/a" },
        { aleman: "außer", espanol: "excepto" }, 
        { aleman: "ich esse nichts außer Pizza", espanol: "no como nada excepto Pizza" },
        { aleman: "backen, backte, hat gebackt", espanol: "hornear" },
        { aleman: "das Lebensmittel", espanol: "el alimento" },
        { aleman: "die Bohne ", espanol: "la judía" },
        { aleman: "braten, briet, hat gebraten", espanol: "asar" },
        { aleman: "das Hähnchen", espanol: "el pollo" },
        { aleman: "die Pommes", espanol: "las patatas fritas" },
        { aleman: "das Rezept", espanol: "la receta" },
        { aleman: "schädlich, schädlicher, am schädlichsten", espanol: "perjudicial" },
        { aleman: "scharf, schärfer, am schärfsten", espanol: "picante" },
        { aleman: "der Topf", espanol: "la olla" },
        { aleman: "voll, völler,am völlsten", espanol: "lleno" },
        { aleman: "die Zitrone", espanol: "el limón" },
        { aleman: "sparen, sparte, hat gespart", espanol: "ahorrar" },
        { aleman: "das Licht", espanol: "la luz" },
        { aleman: "das Meer", espanol: "el mar" },
        { aleman: "die Pflanze", espanol: "la planta" },
        { aleman: "die Zukunft", espanol: "el futuro" },
        { aleman: "ändern, änderte, hat geändert", espanol: "cambiar" },
        { aleman: "gegen", espanol: "contra" },
        { aleman: "recyceln", espanol: "reciclar" },
        { aleman: "der Strom", espanol: "la energía" },
        { aleman: "entwerfen, entwarf, hat entworfen", espanol: "hacer un esbozo" },
        { aleman: "pflanzen, pflanzte, hat gepflanzt", espanol: "plantar" },
        { aleman: "tun, tat, hat getan", espanol: "hacer" },
        { aleman: "der Fernseher", espanol: "el televisor" },
        { aleman: "laufen, lief, ist gelaufen", espanol: "correr" },
        { aleman: "deutlich", espanol: "claro" },
        { aleman: "verbrauchen, verbrauchte, hat verbraucht", espanol: "consumir" },
        { aleman: "verwenden", espanol: "usar" },
        { aleman: "wenig, weniger, am wenigsten", espanol: "poco" },
        { aleman: "folgen, folgte, ist gefolgt", espanol: "seguir" },
        { aleman: "lachen, lachte, hat gelacht", espanol: "reír" },
        { aleman: "Es schüttet wie aus Eimern", espanol: "llueve a cántaros" },
        { aleman: "Es ist windig", espanol: "hace viento" },
        { aleman: "Es ist neblig", espanol: "hay niebla" },
        { aleman: "Es ist bewölkt", espanol: "está nublado" },
        { aleman: "Es ist kühl", espanol: "hace fresco" },
        { aleman: "Es ist heiß", espanol: "hace calor" },
        { aleman: "Es ist kalt", espanol: "hace frío" },
        { aleman: "Es ist sonnig", espanol: "hace sol" },
        { aleman: "Es ist warm", espanol: "hace calor" }, 
        { aleman: "Es ist trocken", espanol: "está seco" },
        { aleman: "Es ist schwül", espanol: "está húmedo" },
        { aleman: "Es ist stürmisch", espanol: "hay tormenta" },
        { aleman: "dunkel, dunkler, am dunkelsten", espanol: "oscuro" }
        
        
      ]
    },
    {
      id: 7,
      nombre: "leccion 7 ",
      palabras: [
        { aleman: "das Erdgeschoss", espanol: "la planta baja" },
        { aleman: "der Stock", espanol: "la planta" },
        { aleman: "der Aufzug", espanol: "el ascensor" },
        { aleman: "der Balkon", espanol: "el balcón" },
        { aleman: "das Dach", espanol: "el tejado" },
        { aleman: "die Garage", espanol: "el garaje" },
        { aleman: "der Garten", espanol: "el jardín" },
        { aleman: "der Keller", espanol: "el sótano" },
        { aleman: "die Treppe", espanol: "la escalera" },
        { aleman: "das Thema", espanol: "el tema" },
        { aleman: "zuerückgeben, gab zurück, hat zurückgegeben", espanol: "devolver" },
        { aleman: "der Fotoapparat", espanol: "la cámara de fotos" },
        { aleman: "drinnen", espanol: "dentro" },
        { aleman: "kaputt", espanol: "roto" },
        { aleman: "putzen, putzte, hat geputzt", espanol: "limpiar" },
        { aleman: "schmutzig, schmutziger, am schmutzigsten", espanol: "sucio" },
        { aleman: "verpassen, verpasste, hat verpasst", espanol: "dejar pasar" },
        { aleman: "die Verspätung", espanol: "el retraso" },
        { aleman: "schrecklich, schrecklicher, am schrecklichsten", espanol: "horrible" },
        { aleman: "vereinbaren, vereinbart, hat vereinbart", espanol: "acordar" },
        { aleman: "bequem, bequemer, am bequemsten", espanol: "cómodo" },
        { aleman: "hässlich, hässlicher, am hässlichsten", espanol: "feo" },
        { aleman: "etwas holen, holte etwas, hat etwas geholt", espanol: "recoger algo" },
        { aleman: "öffnen, öffnete, hat geöffnet", espanol: "abrir" },
        { aleman: "prüfen, prüfte, hat geprüft", espanol: "ha examinado" },
        { aleman: "zuletzt", espanol: "por último" },
        { aleman: "vorne", espanol: "delante" }, 
        { aleman: "dick, dicker, am dicksten", espanol: "gordo/a" },
        { aleman: "freundlich, freundlicher, am freundlichsten", espanol: "amable" },
        { aleman: "die Rechnung", espanol: "la factura" },
        { aleman: "hart, härter, am härtesten ", espanol: "duro/a" },
        { aleman: "rund, runder, am rundesten", espanol: "redondo/a" },
        { aleman: "weich, weicher, am weichsten", espanol: "blando" },
        { aleman: "fertig machen", espanol: "terminar" },
        { aleman: "hinten", espanol: "atrás" }
      ]
    },
   {
      id: 8,
      nombre: "leccion 8 ",
      palabras: [
        { aleman: "das Gesicht", espanol: "la cara" },
        { aleman: "die Kette", espanol: "el collar" },
        { aleman: "passen, passte, hat gepasst", espanol: "quedar" },
        { aleman: "der Ring", espanol: "el anillo" },
        { aleman: "der Rucksack", espanol: "la mochila" },
        { aleman: "der Stiefel", espanol: "la bota" },
        { aleman: "der Strand", espanol: "la playa" },
        { aleman: "das Angebot", espanol: "la oferta" },
        { aleman: "bestellen, bestellte, hast bestellt", espanol: "pedir" },
        { aleman: "günstig, günstiger, am günstigsten", espanol: "barato" },
        { aleman: "der Mantel", espanol: "el abrigo" },
        { aleman: "die Mode", espanol: "la moda" },
        { aleman: "Wie schade!", espanol: "¡Qué pena!" },
        { aleman: "schon", espanol: "ya" },
        { aleman: "Die Jacke steht dir gut", espanol: "la chaqueta te queda bien" },
        { aleman: "Diese Farbe passt dir gut", espanol: "este color te queda bien" },
        { aleman: "wenigstens", espanol: "por lo menos" },
        { aleman: "die Bäckerei", espanol: "la panadería" },
        { aleman: "der Einkauf", espanol: "la compra" },
        { aleman: "zu eng", espanol: "demasiado estrecho" },
        { aleman: "zu breit", espanol: "demasiado ancho" },
        { aleman: "zu lang", espanol: "demasiado largo" },
        { aleman: "zu klein", espanol: "demasiado pequeño" },
        { aleman: "zu groß", espanol: "demasiado grande" },
        { aleman: "der Laden", espanol: "la tienda" },
        { aleman: "das Kaufhaus", espanol: "grandes almacenes" },
        { aleman: "weit", espanol: "ancho" },
        { aleman: "arm", espanol: "pobre" },
        { aleman: "austragen, trug aus, hat ausgetragen", espanol: "repartir" },
        { aleman: "bar zahlen, zahlte bar, hat bar gezahlt", espanol: "pagar en efectivo" },
        { aleman: "sich beschweren, beschwerte sich, hat sich beschwert", espanol: "quejarse" },
        { aleman: "der Führerschein", espanol: "el carnet de conducir" },
        { aleman: "genug", espanol: "suficiente" },
        { aleman: "geschieden sein", espanol: "estar divorciado/a" },
        { aleman: "der Job", espanol: "el trabajo" },
        { aleman: "das Konto", espanol: "la cuenta bancaria" },
        { aleman: "meistens", espanol: "la mayoría de las veces" },
        { aleman: "der Motorroller", espanol: "el scooter" },
        { aleman: "notwendig", espanol: "necesario" },
        { aleman: "pro", espanol: "por" },
        { aleman: "einmal pro Woche", espanol: "una vez a la semana" },
        { aleman: "raten, riet, hat geraten", espanol: "adivinar" },
        { aleman: "regelmäßig", espanol: "regularmente" },
        { aleman: "der Rest", espanol: "el resto" },
        { aleman: "sparen, sparte, hat gespart", espanol: "ahorrar" }, 
        { aleman: "überweisen, überwies, hat überwiesen", espanol: "transferir" },
        { aleman: "verdienen, verdiente, hat verdient", espanol: "ganar dinero" },
        { aleman: "bezahlen, bezahlte, hat bezahlt", espanol: "pagar" },
        { aleman: "das Glück", espanol: "la suerte" },
        { aleman: "reparieren, reparierte, hat repariert", espanol: "reparar" },
        { aleman: "der Friseur", espanol: "el peluquero" },
        { aleman: "genau", espanol: "exacto" },
        { aleman: "recht haben", espanol: "tener razón" },
        { aleman: "ausgeben, gab aus, hat ausgegeben", espanol: "gastar" },
        { aleman: "ich gebe mein Taschengeld für Bücher aus", espanol: "gasto mi paga en libros" },
        { aleman: "bekommen, bekam, hat bekommen", espanol: "recibir" },
        { aleman: "fliegen, flog, ist geflogen", espanol: "volar" },
        { aleman: "der Wunsch", espanol: "el deseo" }
        
      ]
    },
    {
      id: 9,
      nombre: "leccion 9 ",
      palabras: [
        { aleman: "baden, badete, hat gebadet", espanol: "bañarse" },
        { aleman: "die Natur", espanol: "la naturaleza" },
        { aleman: "nebenan", espanol: "al lado" },
        { aleman: "der Ring", espanol: "el anillo" },
        { aleman: "der Verkehr", espanol: "el tráfico" },
        { aleman: "das Land", espanol: "el campo" },
        { aleman: "die Bibliothek", espanol: "la biblioteca" },
        { aleman: "die Brücke", espanol: "el puente" },
        { aleman: "der Flohmarkt", espanol: "el rastro" },
        { aleman: "die Haltestelle", espanol: "la parada" },
        { aleman: "die Bushaltestelle", espanol: "la parada de autobús" },
        { aleman: "der Kindergarten", espanol: "la guardería" },
        { aleman: "die Küche", espanol: "la cocina" },
        { aleman: "die Kreuzung", espanol: "el cruce" },
        { aleman: "Die Polizei", espanol: "la policía" },
        { aleman: "Die Post", espanol: "Oficina de correos" },
        { aleman: "das Rathaus", espanol: "el ayuntamiento" },
        { aleman: "das Reisebüro", espanol: "la agencia de viajes" },
        { aleman: "sizen, saß, hat gesessen", espanol: "estar sentado" },
        { aleman: "die Straße", espanol: "la calle" },
        { aleman: "der Supermarkt", espanol: "el supermercado" },
        { aleman: "die Ampel", espanol: "el semáforo" },
        { aleman: "stehen, stand, hat gestanden", espanol: "estar de pie" },
        { aleman: "der Ort", espanol: "el lugar" },
        { aleman: "der Kiosk", espanol: "el quiosco" },
        { aleman: "das Dorf", espanol: "el pueblo" },
        { aleman: "die Zeitschrift", espanol: "la revista" },
        { aleman: "die Ecke", espanol: "la esquina" },
        { aleman: "der Unterricht", espanol: "la clase" },
        { aleman: "typisch", espanol: "típico" },
        { aleman: "die Anmeldung", espanol: "la inscripción" },
        { aleman: "unterschreiben, unterschrieb, hat unterschrieben", espanol: "firmar" },
        { aleman: "das Formular", espanol: "el formulario" },
        { aleman: "ausfüllen, füllte aus, hat ausgefüllt,", espanol: "rellenar" },
        { aleman: "der Ausweiss", espanol: "el carnet de identidad" },
        { aleman: "bestätigen, bestätigte, hat bestätigt", espanol: "confirmar" },
        { aleman: "der Familienname", espanol: "el apellido" },
        { aleman: "geboren", espanol: "nacido" },
        { aleman: "das Geburtsjahr", espanol: "el año de nacimiento" },
        { aleman: "der Geburtsort", espanol: "el lugar de nacimiento" },
        { aleman: "die Hausnummer", espanol: "el número de casa" },
        { aleman: "hiermit", espanol: "por la presente" },
        { aleman: "die Postleitzahl", espanol: "código postal" },
        { aleman: "der Unterschrift", espanol: "la firma" },
        { aleman: "der Vorname", espanol: "el nombre" }, 
        { aleman: "hängen, hing, hat gehängen", espanol: "estar colgado" },
        { aleman: "legen, legte, hat gelegt", espanol: "poner tumbado" },
        { aleman: "hängen, hängte, hat gehängt", espanol: "colgar" },
        { aleman: "liegen, lag, hat gelegen", espanol: "estar tumbado" },
        { aleman: "stellen, stellte, hat gestellt", espanol: "poner de pie" },
        { aleman: "setzen, setzte, hat gesetzt", espanol: "sentar" },
        { aleman: "wo? (Dativ)", espanol: "¿dónde?" },
        { aleman: "wohin? (Akusativ)", espanol: "¿a dónde?" },
        { aleman: "vor", espanol: "delante" },
        { aleman: "hinter", espanol: "detrás" },
        { aleman: "auf", espanol: "encima" },
        { aleman: "unter", espanol: "debajo" },
        { aleman: "in", espanol: "dentro" },
        { aleman: "neben", espanol: "al lado" },
        { aleman: "zwischen", espanol: "entre" },
        { aleman: "über", espanol: "por encima de" },
        { aleman: "an", espanol: "junto a" },
        { aleman: "vorne", espanol: "delante" },
        { aleman: "hinten", espanol: "detrás" },
        { aleman: "rechts", espanol: "a la derecha" },
        { aleman: "links", espanol: "a la izquierda" },
        { aleman: "draußen", espanol: "fuera" },
        { aleman: "drinnen", espanol: "dentro" },
        { aleman: "oben", espanol: "arriba" },
        { aleman: "unten", espanol: "abajo" },
        { aleman: "da", espanol: "allí" },
        { aleman: "dort", espanol: "allí" },
        { aleman: "hier", espanol: "aquí" },
        { aleman: "dorthin", espanol: "allí" },
        { aleman: "dahin", espanol: "allí" },
        { aleman: "zeichnen", espanol: "dibujar" },
        { aleman: "faul", espanol: "vago/a" },
        { aleman: "weit", espanol: "lejos" },
        { aleman: "die Mitternacht", espanol: "la medianoche" },
        { aleman: "der Nachmittag", espanol: "la tarde" },
        { aleman: "der Abend", espanol: "la noche" },
        { aleman: "der Morgen", espanol: "la mañana" },
        { aleman: "die Nacht", espanol: "la noche" },
        { aleman: "der Tag", espanol: "el día" },
        { aleman: "der Monat", espanol: "el mes" },
        { aleman: "das Jahr", espanol: "el año" },
        { aleman: "der Frühling", espanol: "la primavera" },
        { aleman: "der Sommer", espanol: "el verano" },
        { aleman: "der Herbst", espanol: "el otoño" },
        { aleman: "der Winter", espanol: "el invierno" },
        { aleman: "die Woche", espanol: "la semana" },
        { aleman: "der Montag", espanol: "el lunes" },
        { aleman: "der Dienstag", espanol: "el martes" },
        { aleman: "der Mittwoch", espanol: "el miércoles" },
        { aleman: "der Donnerstag", espanol: "el jueves" },
        { aleman: "der Freitag", espanol: "el viernes" },
        { aleman: "der Samstag", espanol: "el sábado" },
        { aleman: "der Sonntag", espanol: "el domingo" },
        { aleman: "die Uhrzeit", espanol: "la hora" },
        { aleman: "die Minute", espanol: "el minuto" },
        { aleman: "die Sekunde", espanol: "el segundo" },
        { aleman: "die Stunde", espanol: "la hora" },
        { aleman: "beraten, beriet, hat beraten", espanol: "aconsejar" }
        
      ]
    },
   {
      id: 10,
      nombre: "leccion 10 ",
      palabras: [
        { aleman: "das Abitur", espanol: "la selectividad" },
        { aleman: "der Fehler", espanol: "el error" },
        { aleman: "fleißig, fleißiger, am fleißigsten", espanol: "trabajador/a" },
        { aleman: "pünktlich, pünktlicher, am pünklichsten", espanol: "puntual" },
        { aleman: "rechnen, rechnete, hat gerechnet", espanol: "calcular" },
        { aleman: "streng, strenger, am strengsten", espanol: "esctricto/a" },
        { aleman: "der Stundenplan", espanol: "el horario" },
        { aleman: "stören, störte, hat gestört", espanol: "molestar" },
        { aleman: "der Feiertag", espanol: "el día festivo" },
        { aleman: "sich freuen, freute sich, hat sich gefreut", espanol: "alegrarse" },
        { aleman: "hoffentlich", espanol: "ojalá" },
        { aleman: "die Mannschaft", espanol: "el equipo" },
        { aleman: "schimpfen, schimpfte, hat geschimpft", espanol: "regañar" },
        { aleman: "wahrscheinlich", espanol: "probablemente" },
        { aleman: "wegnehmen, nahm weg, hat weggenommen", espanol: "quitar" },
        { aleman: "wiederholen, wiederholte, hat wiederholt", espanol: "repetir" },
        { aleman: "der Apparat", espanol: "el aparato" },
        { aleman: "die Insel", espanol: "la isla" },
        { aleman: "sich kümmern (um), kümmerte sich (um), hat sich (um) gekümmert", espanol: "cuidar de" },
        { aleman: "langsam, langsamer, am langsamsten", espanol: "lento" },
        { aleman: "das Medikament", espanol: "el medicamento" },
        { aleman: "Medikamente nehmen", espanol: "tomar medicamentos" },
        { aleman: "müde, müder, am müdesten", espanol: "estar de pie" },
        { aleman: "der Schmerz", espanol: "el dolor" },
        { aleman: "schwach, schwächer, am schwächsten", espanol: "débil" },
        { aleman: "ein schwerer Unfall", espanol: "un accidente grave" },
        { aleman: "umziehen, zog um, ist umgezogen", espanol: "mudarse" },
        { aleman: "untersuchen, untersuchte, hat untersucht", espanol: "examinar" },
        { aleman: "die Hilfe", espanol: "la ayuda" },
        { aleman: "träumen (von), träumte (von), hat (von) geträumt", espanol: "soñar (con)" },
        { aleman: "zuhören, hörte zu, hat zugehört", espanol: "escuchar con atención" },
        { aleman: "kontrollieren, kontrollierte, hat kontrolliert", espanol: "controlar" },
        { aleman: "der Blog", espanol: "el blog" }
        
      ]
    },
   {
      id: 11,
      nombre: "leccion 11 ",
      palabras: [
        { aleman: "ankommen, kam an, ist angekommen", espanol: "llegar" },
        { aleman: "der Flughafen", espanol: "el aeropuerto" },
        { aleman: "das Flugzeug", espanol: "el avión" },
        { aleman: "das Gepäck", espanol: "el equipaje" },
        { aleman: "halten, hielt, gehalten", espanol: "parar" },
        { aleman: "das Schild", espanol: "el letrero" },
        { aleman: "die Ankunft", espanol: "la llegaada" },
        { aleman: "der Besuch", espanol: "la visita" },
        { aleman: "die Sehenswürdigkeit", espanol: "el lugar de interés" },
        { aleman: "der Zoo", espanol: "el zoo" },
        { aleman: "der Eingang", espanol: "la entrada" },
        { aleman: "Spanien liegt in Europa", espanol: "España está en Europa" },
        { aleman: "der Tourist", espanol: "el turista" },
        { aleman: "die Touristin", espanol: "la turista" },
        { aleman: "das Zentrum", espanol: "el centro" },
        { aleman: "besichtigen", espanol: "visitar" },
        { aleman: "sicher, sicherer, am sichersten", espanol: "seguro" },
        { aleman: "die Fahrkarte", espanol: "el billete" },
        { aleman: "gültig, gültiger, am gültigsten", espanol: "válido" },
        { aleman: "der Markt", espanol: "el mercado" },
        { aleman: "der Kellner", espanol: "el camarero" },
        { aleman: "die Kellnerin", espanol: "la camarera" },
        { aleman: "die Grippe", espanol: "la gripe" },
        { aleman: "wiederholen, wiederholte, hat wiederholt", espanol: "repetir" },
        { aleman: "die Party", espanol: "la fiesta" },
        { aleman: "sich bedanken, bedankte sich, hat sich bedankt", espanol: "agradecer" },
        { aleman: "zurückfahre fuhr zurück, ist zurückgefahren", espanol: "volver" },
        { aleman: "die Hauptstadt", espanol: "la capital" },
        { aleman: "aufgeregt, aufgeregter, am aufgeregtesten", espanol: "emocionado, nervioso" },
        { aleman: "das Ausland", espanol: "el país extranjero" },
        { aleman: "außerhalb", espanol: "fuera de" },
        { aleman: "innerhalb", espanol: "dentro de" },
        { aleman: "fremd", espanol: "desconocido/a" },
         { aleman: "die Hochzeit", espanol: "la boda" },
        { aleman: "die kultur", espanol: "la cultura" },
        { aleman: "österreichisch", espanol: "austriaco/a" },
        { aleman: "schwierig, schwieriger, am schwierigsten", espanol: "difícil" },
        { aleman: "vorher", espanol: "antes" }
        
      ]
    },
    {
      id: 12,
      nombre: "leccion 12 ",
      palabras: [
        { aleman: "der Beruf", espanol: "la profesión" },
        { aleman: "das Büro", espanol: "la oficina" },
        { aleman: "entwickeln, entwickelte, hat entwickelt", espanol: "desarrollar" },
        { aleman: "die Fabrik", espanol: "la fábrica" },
        { aleman: "der Motor", espanol: "el motor" },
        { aleman: "der Nordpol", espanol: "el polo norte" },
        { aleman: "das Tierheim", espanol: "casa de acogida para animales" },
        { aleman: "werde, wurde, ist geworden", espanol: "llegar a ser" },
        { aleman: "ich werde Ärztin ", espanol: "seré médica" },
        { aleman: "die Werkstatt", espanol: "el taller" },
        { aleman: "arbeitslos", espanol: "desempleado" },
        { aleman: "basteln, bastelte, hat gebastelt", espanol: "hacer manualidades" },
        { aleman: "die Hausfrau", espanol: "la ama de casa" },
        { aleman: "der Hausmann", espanol: "el amo de casa" },
        { aleman: "das Labor", espanol: "el laboratorio" },
        { aleman: "liefern, lieferte, hat geliefert", espanol: "repartir" },
        { aleman: "die Wissenschaft", espanol: "la ciencia" },
        { aleman: "der Wissenschaftler", espanol: "el científico" },
        { aleman: "die Wissenschaftlerin", espanol: "la científica" },
        { aleman: "die Aussbildung", espanol: "la formación profesional" },
        { aleman: "der, die Auszubildende", espanol: "aprendiz" },
        { aleman: "vermuten, vermutete, hat vermutet", espanol: "suponer" },
        { aleman: "die Bewerbung", espanol: "solicitud" },
        { aleman: "der Chef", espanol: "el jefe" },
        { aleman: "die Chefin", espanol: "la jefa" },
        { aleman: "das Stundium", espanol: "la carrera universitaria" },
        { aleman: "einfach", espanol: "fácil" },
        { aleman: "die Entscheidung", espanol: "la decisión" },
        { aleman: "eine Entscheidung treffen", espanol: "tomar una decisión" },
        { aleman: "das Fach", espanol: "la asignatura" },
        { aleman: "der Krankenpfleger", espanol: "el enfermero" },
        { aleman: "die Krankeschwester", espanol: "la enfermera" },
        { aleman: "nützlich", espanol: "útil" },
        { aleman: "das Praktikum", espanol: "la práctica" },
        { aleman: "die Stelle", espanol: "el puesto de trabajo" },
        { aleman: "das Stipendium", espanol: "la beca" },
        { aleman: "der Student", espanol: "el estudiante" },
        { aleman: "studieren, studierte, hat studiert", espanol: "estudiar" },
        { aleman: "theoretisch", espanol: "en teoría" },
        { aleman: "die Vorlesung", espanol: "la clase magistral" },
        { aleman: "herstellen, stellte her, hat hergestellt", espanol: "fabricar, producir" },
        { aleman: "nicht... sondern...", espanol: "no... sino..." },
        { aleman: "aud keinen Fall", espanol: "en absoluto" },
        { aleman: "der Mitarbeiter", espanol: "empleado" },
        { aleman: "die Mitarbeiterin", espanol: "la empleada" },
         { aleman: "der Brief", espanol: "la carta" },
        { aleman: "schneiden, schnitt, hat geschnitten ", espanol: "cortar" },
        { aleman: "von... bis...", espanol: "desde... hasta..." },
        { aleman: "aussteigen, stieg aus, ist ausgestiegen", espanol: "bajarse" },
        { aleman: "einsteigen, stieg ein, ist eingestiegen", espanol: "subirse" },
        { aleman: "umsteigen, stieg um, ist umgestiegen", espanol: "hacer trasbordo" },
        { aleman: "der Fahrplan", espanol: "itinerario de transportes públicos" },
        { aleman: "die Haltestelle", espanol: "la parada" },
        { aleman: "die Landschaft", espanol: "el paisaje" },
        { aleman: "die Sommerferien", espanol: "las vacaciones de verano" },
        { aleman: "der Stoff", espanol: "la materia" },
        { aleman: "Im Physik muss ich viel Stoff wiederholen", espanol: "en física tengo que recuperarmucha materia" },
        { aleman: "verbessern, verbesserte, hat verbessert", espanol: "mejorar" },
        { aleman: "Bescheid geben, gab Bescheid, hat Bescheid gegeben", espanol: "informar" },
        { aleman: "buchen, buchte, hat gebucht", espanol: "reservar" },
        { aleman: "dorthin", espanol: "allí" },
        { aleman: "erreichen, erreichte, hat erreicht", espanol: "alcanzar" },
        { aleman: "hoffen, hoffte, hat gehofft", espanol: "tener esperanza" },
        { aleman: "der ICE", espanol: "el Intercity Express" },
        { aleman: "süß", espanol: "dulce" },
        { aleman: "unternehmen, unternahm, hat unternommen", espanol: "emprender" },
        { aleman: "bestehen, bestand, hast bestanden", espanol: "aprobar" },
        { aleman: "das Hotel", espanol: "el hotel" },
        { aleman: "sich melden, meldete sich, hat sich gemeldet", espanol: "avisar" },
        { aleman: "melde dich , wenn du da bist!", espanol: "avísame cuando llegues" },
        { aleman: "nach", espanol: "después de" },
        { aleman: "übermorgen", espanol: "pasado mañana" },
        { aleman: "vorgestern", espanol: "antes de ayer" },
        { aleman: "verreisen, verreiste, hat verreist", espanol: "viajar" },
        { aleman: "wünschen, wünschte, hat gewünscht", espanol: "desear" },
        { aleman: "ich wünsche dir schöne Ferien", espanol: "te deseo felices vacaciones" },
        { aleman: "das Zelt", espanol: "la tienda de campaña" },
        { aleman: "das Zeugnis", espanol: "el certificado" }
        
      ]
    },
  ]
};
